import 'package:get/get.dart';

class Mylocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'Settings',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'language': 'Language',
      'english': 'English',
      'turkish': 'Turkish',
      'Breaking': 'Breaking News',
      'View All': 'View All',
      'Recommendations': 'Recommendations',
      'Hello3': 'Please select your interests',
      'Alert': 'Alert',
      'alertTXT':
          'If you do not specify your interests, it will be automatically set to general',
      'Cancel': 'Cancel',
      'OK': 'OK',
      'Get_Started': 'Get Started',
      'Next': 'Next',
      "Ask": "Ask AI assistant",
      'share': 'Check out this news article!',
      'wait': 'Please wait...',
      'Close': 'Close',
      'Settings': 'Settings',
      'Mod': 'Dark Mode',
      'Notifications': 'Notifications',
      'Language': 'Language',
      'Hava': 'Weather',
      'Hava2': 'Today\'s Weather',
      'Hava3': 'Expected Event:',
      'Hava4': 'Humidity (%):',
      'Hava5': 'Minimum:',
      'Hava6': 'Maximum:',
      'Hava7': 'Upcoming Days',
      'About': 'About Us',
      'Namaz': 'Prayer Times',
      'Chatbot': 'Chatbot',
      'message': 'Type your message here...',
      'cat': 'Categories',
    },
    'tr_TR': {
      'title': 'Ayarlar',
      'dark_mode': 'Karanlık Mod',
      'notifications': 'Bildirimler',
      'language': 'Dil',
      'english': 'İngilizce',
      'turkish': 'Türkçe',
      'Breaking': 'Son Dakika',
      'View All': 'Tümünü Gör',
      'Recommendations': 'Öneriler',
      'Hello3': 'Lütfen ilgi alanlarınızı seçin',
      'Alert': 'Uyarı',
      'alertTXT':
          'Eğer ilgi alanlarınızı belirtmezseniz, otomatik olarak genel olarak ayarlanacaktır',
      'Cancel': 'İptal',
      'OK': 'Onaylıyorum',
      'Get_Started': 'Başlayalım',
      'Next': 'İleri',
      "Ask": "Yapay Zeka Asistanına Sor",
      'share': 'Bu haber makalesini kontrol edin!',
      'wait': 'Lütfen bekleyin...',
      'Close': 'Kapat',
      'Settings': 'Ayarlar',
      'Mod': 'Karanlık Mod',
      'Notifications': 'Bildirimler',
      'Language': 'Dil',
      'Hava': 'Hava durumu',
      'Hava2': 'Bugün Hava Durumu',
      'Hava3': 'Beklenen Hadise :',
      'Hava4': 'Nem (%)	 :',
      'Hava5': 'En Düşük	 :',
      'Hava6': 'En Yüksek	 :',
      'Hava7': 'Gelecek Günler',
      'About': 'Hakkımızda',
      'Namaz': 'Namaz Vakitleri',
      'Chatbot': 'Sohbet Botu',
      'message': 'Mesajınızı buraya yazın...',
      'cat': 'Kategoriler',
    },
  };
}
