// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yVedWl9IINhqkx5JXpj2KDcvuVMoMi4',
    appId: '1:205700197868:web:0b8689cf37781caab664c9',
    messagingSenderId: '205700197868',
    projectId: 'news-app-2db23',
    authDomain: 'news-app-2db23.firebaseapp.com',
    storageBucket: 'news-app-2db23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbyOnmYldSAiUIxf8ZqGVG37eQCc3NoA',
    appId: '1:205700197868:android:95b1b1fb18000cd6b664c9',
    messagingSenderId: '205700197868',
    projectId: 'news-app-2db23',
    storageBucket: 'news-app-2db23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3xpuum9GX7Q8w09CcWtAGQw0_OBhHq6s',
    appId: '1:205700197868:ios:0925857fb91faa8fb664c9',
    messagingSenderId: '205700197868',
    projectId: 'news-app-2db23',
    storageBucket: 'news-app-2db23.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3xpuum9GX7Q8w09CcWtAGQw0_OBhHq6s',
    appId: '1:205700197868:ios:0925857fb91faa8fb664c9',
    messagingSenderId: '205700197868',
    projectId: 'news-app-2db23',
    storageBucket: 'news-app-2db23.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1yVedWl9IINhqkx5JXpj2KDcvuVMoMi4',
    appId: '1:205700197868:web:d1be342c779bf1e2b664c9',
    messagingSenderId: '205700197868',
    projectId: 'news-app-2db23',
    authDomain: 'news-app-2db23.firebaseapp.com',
    storageBucket: 'news-app-2db23.firebasestorage.app',
  );
}
